apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-world-staging 
images:
  - name: octopus-hello-world
    newName: kubeconnademo.azurecr.io/octopus-hello-world
    newTag: #{Octopus.Action.Package[octopus-hello-world].PackageVersion}

resources:
- ../../base