apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-world-staging 
images:
  - name: octopus-hello-world-#{Octopus.Environment.Name}
    newName: kubeconnademo.azurecr.io/octopus-hello-world
    newTag: main-19203778285

resources:
- ../../base