apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: octopus-hello-world
  newName: ghcr.io/mjrichardson/octopus-hello-world
  newTag: #{Octopus.Action.Package[nginx].PackageVersion}

resources:
- ../../base